### ISSUE TITLE
Version 0.99.2 will be released in 2024?

### ISSUE THREAD

**Issue by castig** [matrix-org/sliding-sync#161]
On the ReadMe it says "Version 0.99.2 will be released on 2024/07/27" — is that supposed to be 2023? Or is the release in 2024? 

I'm also curious if there's an estimated release date for V1? 

Thanks for all your hard work! This is incredible.

**Comment by kegsay** [comment]
No, this is a typo, thanks.

**Comment by DMRobertson** [comment]
Fixed, but note that section of the readme includes the date of the MSC draft implemented by that version. I have tried to clarify this, but to be honest I think it is still a bit confusing.

**Comment by afonsofrancof** [comment]
Any ETA on when this will be merged into synapse? (I assume it's planned to be merged)
