### ISSUE TITLE
Database corruption when servers backfill over federation

### ISSUE THREAD

**Issue by kegsay** [matrix-org/sliding-sync#192]
Consider:

- Bob on his server invites Alice to a room.
- Alice joins the room first over federation. Proxy does the right thing and sets her membership to join. There is no timeline though due to not having backfilled.
- Alice's client backfills in the room which pulls in the invite event, but the SS proxy doesn't see it as it's backfill, not /sync.
- Charlie joins the same room via SS, which makes the SS proxy see 50 timeline events, which includes the invite. As the proxy has never seen this invite event before, it assumes it is newer than the join event and inserts it, corrupting state.

To fix this:
- SELECT nids for all events prior to insertion.
- Find the lowest-index which has a NID and drop all events earlier than this as they are backfilled.
- Discard the state block when this happens, as it cannot be trusted to do the right thing now that we are dropping parts of the timeline.

**Comment by DMRobertson** [comment]
> * Find the lowest-index which has a NID and drop all events earlier than this as they are backfilled.

`earlier` in what sense---origin server TS?
