### ISSUE TITLE
Read Receipts only on subscribed rooms

### ISSUE THREAD

**Issue by manuroe** [matrix-org/sliding-sync#199]
Currently, EX cannot enable RRs because there are sent for all rooms. We are back to a sync v2 behavior in terms of performance: much more bandwidth usage, responses slower to get and process, longer syncing spinner...

A Matrix client should be able to get RRs only when the UI needs it, ie on the timeline screen for EX.

**Comment by kegsay** [comment]
So the RR extension does have the ability to filter only RRs for certain rooms, as per the proposal https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/ssext-receipts/proposals/3960-sliding-sync-receipts.md#proposal

This issue actually wants something different, specifically the ability to set a wildcard `*` on `rooms`, such that _any room subscription_ will automatically send RRs. This currently does not exist.
