### ISSUE TITLE
Restarting the proxy and resuming sync from `?pos=N` responds with "Session expired"

### ISSUE THREAD

**Issue by turt2live** [matrix-org/sliding-sync#20]
**To Reproduce**
1. Start a new sync, without `session_id`, to get a few `pos` responses
2. Restart the proxy
3. Try to request the next batch with `?pos=2` (or whatever your number is from step 1)

**Comment by kegsay** [comment]
This isn't intended to ever work as positions are only stored in memory. Restarting the proxy then invalidates all open connections causing them to reset. When the proxy implements bandwidth saving measures like described on the MSC then it will remember what it has told the client.
