### ISSUE TITLE
Add Sentry support

### ISSUE THREAD

**Issue by kegsay** [matrix-org/sliding-sync#21]
To make certain errors much more visible.

**Comment by DMRobertson** [comment]
First step would be something that reports errors in responding to incoming sync v3 requests.

**Comment by DMRobertson** [comment]
https://github.com/archdx/zerolog-sentry might be nice to use

**Comment by DMRobertson** [comment]
I think #57 and #67 are a good first pass. It'd be good to feed some more information into sentry (e.g. [usernames](https://docs.sentry.io/platforms/go/enriching-events/identify-user/) or the other tricks described at https://docs.sentry.io/platforms/go/enriching-events/). But it's probably best to see how we use the Sentry reports in practice before going further.

**Comment by DMRobertson** [comment]
Other things I'd like to do:

- [associate incoming requests to a user](https://docs.sentry.io/platforms/go/enriching-events/identify-user/)
- add logging for panics that won't get `recover`ed from
