### ISSUE TITLE
Sliding sync pollers should use `set_presence=offline` when requesting oldschool /sync

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/sliding-sync#217]
`/sync` currently bumps the user's presence timeout. Since SS pollers are active even when the device is offline, this is undesired as the users will be marked as online when they are not. Further, this causes a bit more load on Synapse and also as a consequence causes other sync loop within Synapse to wake up to emit this unwanted presence data to other users who may be syncing.

I suspect this may be contributing to the high CPU usage reported at https://github.com/matrix-org/synapse/issues/15980.

(or, with extra involved effort: find some way to pass the right state through from the client)

Related code: https://github.com/matrix-org/sliding-sync/blob/aadc358581ac78d8248ddd6a65205f15e151bcc9/sync2/client.go#L64 → https://github.com/matrix-org/sliding-sync/blob/aadc358581ac78d8248ddd6a65205f15e151bcc9/sync2/client.go#L88

**Comment by DMRobertson** [comment]
What we really want is a way to express "don't alter presence based on this /sync call". 

The spec is confused and inconsistent here: https://github.com/matrix-org/matrix-spec/issues/1609.

I don't have any strong opinions about what the right thing to do is.
