### ISSUE TITLE
Receiving malformed events should not cascade fail timeline processing

### ISSUE THREAD

**Issue by kegsay** [matrix-org/sliding-sync#223]
Some rooms seem to have invalid events missing a `type` key. This causes the proxy to get upset:
```
ERR V2: failed to accumulate room error="filterTimelineEvents: event malformed: event JSON missing type key"
```
When this happens when processing a timeline block, it causes the entire timeline block to be ignored, rather than just the malformed event. In practice, we probably just want to ignore the malformed event and continue on, rather than drop valid events that happen to be alongside the malformed event.

**Comment by DMRobertson** [comment]
See https://sentry.tools.element.io/organizations/element/issues/69173/?project=56&query=is%3Aunresolved+type&statsPeriod=14d and https://sentry.tools.element.io/organizations/element/issues/78084/?project=56&query=is%3Aunresolved+type&statsPeriod=14d and https://sentry.tools.element.io/organizations/element/issues/74800/?project=56&query=is%3Aunresolved+type&statsPeriod=14d
