### ISSUE TITLE
Going from 0.98.0 to 0.98.1+ does not work

### ISSUE THREAD

**Issue by JacksonChen666** [matrix-org/sliding-sync#23]
# output

```
Sync v3 [0.98.1] ()
00:23:33 INF creating handler
panic: pq: column "membership_events" does not exist
goroutine 1 [running]:
github.com/matrix-org/sliding-sync.Setup({0xc00003003e, 0x21}, {0xc00003400a, 0x4b}, {0xc00003200e, 0x40}, {0x2?, 0x0?, 0x0?})
        /home/matrix-synapse/sliding-sync/v3.go:92 +0x3a5
main.main()
        /home/matrix-synapse/sliding-sync/cmd/syncv3/main.go:89 +0x854

```

# workaround

reverting back to 0.98.0 works, but you're still on 0.98.0 then...

creating a new database for the newer version also works, but now you start from scratch (what i did)

**Comment by kegsay** [comment]
There's no migration support in this project yet so this is expected.

**Comment by JacksonChen666** [comment]
close as not fix or something else?

**Comment by ara4n** [comment]
yes, closed as won't fix - the project doesn't yet support database migration.

**Comment by JacksonChen666** [comment]
> yes, closed as won't fix

github says otherwise (there's another close option for the "no")

<img width="389" alt="kegsay 'closed this as completed', highlighting the 'closed this as completed' part" src="https://user-images.githubusercontent.com/50755746/216316629-379eaa2e-70c9-46d0-b259-826b6576d4eb.png">
