### ISSUE TITLE
Gracefully handle when the DB disappears at runtime

### ISSUE THREAD

**Issue by pmaier1** [matrix-org/sliding-sync#230]
- no critical issues in sentry 
- end-to-end testing with rust SDK, ideally with EX client as well
- Gracefully handle db connection issues / RDS updates from underneath us (to-device msgs)

@kegsay please fill in more details if necessary

**Comment by pmaier1** [comment]
- Sentry looks good for the moment
- No progress on gracefully handling db connection issues => needed for September release
- Still depends on client teams writing e2e tests. TBD

**Comment by hughns** [comment]
I've split out the DB connection handling into https://github.com/matrix-org/sliding-sync/issues/251

**Comment by kegsay** [comment]
https://github.com/matrix-org/sliding-sync/pull/254
