### ISSUE TITLE
Room Heroes

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/sliding-sync#241]
In order to render [stacked avatar clusters](https://www.figma.com/file/iIjwDl9HjaaF1vlDU96h8K/INBOX-%C2%B7-Compound-iOS%2FAndroid-Components?type=design&node-id=468-26319&mode=design&t=MXbTUt6Mu5rSViE7-4), it is desirable to have a flag/extension to request the Room's heroes be included in sync responses.

The clusters have the requirement that these will be displayed in a consistent order and it seems like we should use the hero ordering for this so it matches the generated room name. The linked designs scale up to 4 room members (including the current user), so in theory we only need the first 3 heroes for Element X (which might be a useful data saver instead of all 5)

**Comment by pixlwave** [comment]
Adding a note that this will also be useful for 1:1 DM colour computation.

**Comment by S7evinK** [comment]
(copy and pasting, with some modification)
- If we add a `heroes` flag, this would be per list and result in potentially wasted bandwidth (think of rooms where we have a `m.room.name` or already have an avatar URL)
- Should we try to be "intelligent" and automatically return `heroes` if the room name was calculated using heroes?
- Combination of the above? (as in: we add a `heroes` flag and only return `heroes` if we calculated the name using heroes)

imo, the last option sounds the way to go, as this doesn't return unused (by the client) data

**Comment by poljar** [comment]
How about something like this for an explicitly named room:

```json
{
  "explicit": {
    "name": "my_name"
  }
}
```

And this for a calculated room:
```json
{
  "calculated": {
    "heroes": [
      "@foo:bar"
    ]
  }
}
```

Which would map to this Rust struct:

```rust
#[derive(Serialize, Deserialize)]
enum RoomName {
    #[serde(rename = "calculated")]
    Calculated { heroes: Vec<String> },
    #[serde(rename = "explicit")]
    Explicit { name: String },
}
```

We could use a [internally tagged] representation if you prefer that one, which seems to be more common in the Matrix world.

We could also go a bit further and try to map what we already have in the Rust SDK:
https://github.com/matrix-org/matrix-rust-sdk/blob/dde2f408c5e9449db3f01931ddae3cfd434c2d3d/crates/matrix-sdk-base/src/rooms/mod.rs#L32-L48

Though this enum has the problem that the heroes are flattened out into a string, so we would need to fix that.

I hope that this would also allow @pixlwave to do whatever he needs to do on the app side.

[internally tagged]: https://serde.rs/enum-representations.html#internally-tagged
