### ISSUE TITLE
Duplicate leave events

### ISSUE THREAD

**Issue by kegsay** [matrix-org/sliding-sync#250]
I suspect since https://github.com/matrix-org/sliding-sync/pull/235 we now send N leave events, once per poller as this is now tied to `OnLeftRoom` and isn't de-duped as we explicitly ignore the load position.

Reported by Ivan, running `f73c8e4604d6`

**Comment by S7evinK** [comment]
This should now be fixed by https://github.com/matrix-org/sliding-sync/pull/297
