### ISSUE TITLE
EW: badness with invites

### ISSUE THREAD

**Issue by ara4n** [matrix-org/sliding-sync#26]
I tried to accept an invite on SS EW:
 * It didn't accept
 * I then accepted it on a different client
 * The room is still shown in Invites on SS
 * However, it also seems to have let me join it there.

**Comment by kegsay** [comment]
I believe this was fixed when https://github.com/matrix-org/sliding-sync/issues/35 was fixed. I'm leaving this open until I have SS EW Cypress tests for invites.

**Comment by kegsay** [comment]
Added cypress tests in https://github.com/matrix-org/matrix-react-sdk/pull/8328/commits/7a6b7548cdf21c9793e2b01b1228b58e2c8bdb6f


Closing.
