### ISSUE TITLE
`ping-v10.1` room appears to cause minor race conditions

### ISSUE THREAD

**Issue by turt2live** [matrix-org/sliding-sync#262]
```
ss_sync  | 22:00:03 WRN parseRoomsResponse: prepending state events to timeline after gappy poll prependStateEvents=65 room_id=!ping-v10.1:maunium.net
ss_sync  | 22:00:03 WRN Accumulator.filterAndParseTimelineEvents: seen the same event ID twice, ignoring event_id=$Y3-zTlg4P3O_8kR0UxEZq3eKJ6DUno6rKmLqE_iMRek room_id=!ping-v10.1:maunium.net
```

**Comment by DMRobertson** [comment]
This is a problem with the upstream homeserver sending us the same event more than once in the timeline.

I would suspect Synapse is doing something silly:

- https://github.com/matrix-org/synapse/issues/1995
- https://github.com/matrix-org/synapse/issues/9768
- https://github.com/matrix-org/synapse/issues/11447
- https://github.com/matrix-org/synapse/issues/14539
