### ISSUE TITLE
unsupported protocol scheme

### ISSUE THREAD

**Issue by iraizo** [matrix-org/sliding-sync#265]
Not sure on which repo to create this issue on but sliding-sync is failing when using the testflight version of element x (ios), here are the logs. the homeserver is syn.raizo.dev/raizo.dev

![image](https://github.com/matrix-org/sliding-sync/assets/35413558/5bac4566-2b2f-46aa-9431-c8eb5530c593)

**Comment by DMRobertson** [comment]
@iraizo I expect you have set SYNCV3_SERVER=38.242.224.119; try setting `SYNCV3_SERVER=https://38.242.224.119" and see if that helps.

We should probably make the proxy refuse to start if you haven't specified the protocol in that env var.

**Comment by iraizo** [comment]
Yep, my bad. It works fine now!
