### ISSUE TITLE
Error when pressing "Start Sync"

### ISSUE THREAD

**Issue by ItzYanick** [matrix-org/sliding-sync#27]
I opened `/client/` and entered my access token and then pressed "Start Sync" but all it returns is:

```
Error: /sync returned HTTP 400 HTTP 400 : json: cannot unmarshal array into Go struct field Request.lists of type map[string]sync3.RequestList
```

The console returned the following
```
16:37:45 INF  duration=1000.929606 size=123 status=400

2023-02-09T16:37:49Z ERR failed to read/decode request body | error=json: cannot unmarshal array into Go struct field Request.lists of type map[string]sync3.RequestList
```

I installed using the documentation in the README. Did i miss something?

**Comment by kegsay** [comment]
Yes, sorry the `/client/` test rig needs updating for 0.99. If you use 0.98.x it should work!

**Comment by ItzYanick** [comment]
Oh yea now it works. Thanks!
