### ISSUE TITLE
Docker image doesn't contain any of /client/ assets

### ISSUE THREAD

**Issue by frebib** [matrix-org/sliding-sync#28]
I spent a good half an hour scratching my head, thinking I'd done something wrong. I followed the docs in the README pretty closely but couldn't work out for the life of me why I was getting 404 on the `/client/` paths.

I started with a simple container, orchestrated with Docker Compose as such:
```yaml
services:
  [...]
  slidingsync:
    image: ghcr.io/matrix-org/sliding-sync
    environment:
    - SYNCV3_SECRET=<snip>
    - SYNCV3_SERVER=https://<snip>
    - SYNCV3_DB=host=db dbname=syncv3 sslmode=disable user=syncv3 password=<snip>
    - SYNCV3_BINDADDR=:8008
    depends_on:
    - db
    networks:
      backend:
    restart: on-failure
```
and after futzing with postgres permissions, syncv3 started up, but browsing to the container IP at `/client/` I was getting 404
```
Sync v3 [0.99.0] (613cbd9a670d2cf166a71a182183a5b179a4347a)
10:13:59 INF creating handler
10:13:59 INF retrieved global snapshot from database
10:13:59 INF listening on [::]:8008
10:13:59 INF StartV2Pollers num_devices=0 num_fail_decrypt=0
10:13:59 INF StartV2Pollers finished
10:14:18 INF  duration=0.027891 path=/ size=19 status=404
10:14:19 INF  duration=0.048513 path=/favicon.ico size=19 status=404
10:14:22 INF  duration=0.039538 path=/client size=19 status=404
10:14:35 INF  duration=0.308996 path=/client/ size=19 status=404
10:16:10 INF  duration=0.056527 path=/client/ size=19 status=404
```

After poking in the code, I realised that the client directory is simply a static directory of files, loaded from the current working directory https://github.com/matrix-org/sliding-sync/blob/613cbd9a670d2cf166a71a182183a5b179a4347a/v3.go#L131 and checking inside the container, sure enough, there was no `client` directory to be found anywhere.
I cloned this repo and bind-mounted the /client/ directory into the container, and magically everything seems to work now.

Should the client files be included into the container image?

**Comment by kegsay** [comment]
The client files are test files for development purposes. They aren't intended to be used by end users. Use a sliding sync enabled client like Element X or Element Web.

**Comment by frebib** [comment]
Ah, that explains my confusion. The readme makes it sound like the usage instructions are for "normal" usage and not just development

**Comment by spantaleev** [comment]
I got bitten by this too - trying to hit `/clients/` to see if I've configured the reverse-proxy correctly, only to see it 404 every time. Even without a reverse-proxy (hitting `:8008` directly), I was observing the same, which was causing me to scratch my head.

I suppose the README should be improved.
