### ISSUE TITLE
EW: Settings UI doesn't work

### ISSUE THREAD

**Issue by ara4n** [matrix-org/sliding-sync#28]
Toggling sliders on any of the settings UI doesn't give any local echo at all.

**Comment by kegsay** [comment]
Please can you provide more information on which bits of the UI interacted with, whether they did take effect or not (as in it's just lack of local echo UX), etc.

**Comment by kegsay** [comment]
I can reproduce this - this is User settings, not room settings. It looks like the receipt of global account data is not causing the /sync loop to immediately return, and EW has no local echo for these buttons.
