### ISSUE TITLE
Please explain how to enable sliding-sync at Synapse

### ISSUE THREAD

**Issue by derritter88** [matrix-org/sliding-sync#284]
I installed sliding-sync according to the documentation but unfortunately I cannot make it talk with my Synapse homeserver.
I checked the official Synapse documentation to find if there is config parameter but there is none.

Can someone let me know how I sliding-sync/proxy can work with Synapse?
I am using a dedicated subdomain for each service

**Comment by DMRobertson** [comment]
It is difficult to provide advice without more detail on how you've configured the proxy and what (if any) errors you're seeing.

I would start by sanity checking that from within the proxy's host you can contact Synapse, e.g. with `curl $SYNCV3_SERVER/_matrix/client/versions`, where SYNCV3_SERVER is the environment variable passed to the proxy.

For the time being, please ask the community for support in the [Sliding Sync Discussion room](https://matrix.to/#/#sliding-sync:matrix.org).

**Comment by derritter88** [comment]
Hello @DMRobertson 

thanks for the information.
In general I am running my Synapse server behind an Apache reverse proxy being set up according the documentation.

My `versions` information would be:

```
{
  "versions": [
    "r0.0.1",
    "r0.1.0",
    "r0.2.0",
    "r0.3.0",
    "r0.4.0",
    "r0.5.0",
    "r0.6.0",
    "r0.6.1",
    "v1.1",
    "v1.2",
    "v1.3",
    "v1.4",
    "v1.5",
    "v1.6"
  ],
  "unstable_features": {
    "org.matrix.label_based_filtering": true,
    "org.matrix.e2e_cross_signing": true,
    "org.matrix.msc2432": true,
    "uk.half-shot.msc2666.query_mutual_rooms": true,
    "io.element.e2ee_forced.public": false,
    "io.element.e2ee_forced.private": false,
    "io.element.e2ee_forced.trusted_private": false,
    "org.matrix.msc3026.busy_presence": false,
    "org.matrix.msc2285.stable": true,
    "org.matrix.msc3827.stable": true,
    "org.matrix.msc3440.stable": true,
    "org.matrix.msc3771": true,
    "org.matrix.msc3773": false,
    "fi.mau.msc2815": false,
    "fi.mau.msc2659.stable": true,
    "org.matrix.msc3882": false,
    "org.matrix.msc3881": false,
    "org.matrix.msc3874": false,
    "org.matrix.msc3886": false,
    "org.matrix.msc3912": false,
    "org.matrix.msc3981": false,
    "org.matrix.msc3391": false
  }
}
```

I have installed Synapse from the Matrix Ubuntu repository.

**Comment by derritter88** [comment]
Okay I finally made it with help from the sliding sync community:

1. SYNCV3_SERVER is always the Synapse homeserver (I got confused as the sample URL mentions `https://matrix-client.matrix.org` (client != server).

2. I relied on the .well-known configuration which was generated by Synapse. It is necessary to disable this and create an own, dedicated .well-known site with the same structure as Synapse + the additional proxy URL.
e.g.:
```
{
        "m.server": {
                "base_url": "https://synapse.hostname.tld"
        },
        "m.homeserver": {
                "base_url": "https://synapse.hostname.tld"
        },
        "org.matrix.msc3575.proxy": {
                "url": "https://syncv3.hostname.tld"
        },
        "m.identity_server": {
                "base_url": "https://matrix.org"
        }

}
```

**Comment by floviolleau** [comment]
Hi,

How did you made 2.?

Thanks

**Comment by derritter88** [comment]
@floviolleau You need to create a manual .well-known file and reference it at your webserver.
For apache this would look like `AliasMatch /.well-known/matrix/client /var/www/matrix-synapse/.well-known`

The file itself just needs to contain the text (JSON formatted).

**Comment by floviolleau** [comment]
Hi,

Thanks but how to disable .well-known in synapse?

**Comment by derritter88** [comment]
There is a config parameter within the homeserver.yaml file:

```
serve_server_wellknown: false
```

**Comment by firefoxlover** [comment]
It would be great to know what Servers support Sliding Sync already.

Afaik not even all use Dendrite, so there are a lot of soon deprecated ones out there.

**Comment by spaetz** [comment]
> It would be great to know what Servers support Sliding Sync already.

ALL servers support sliding sync, as SS is just another proxy on top of standard sync functionality. It is relatively independent of the server (which makes it attractive as a common reference implementation).

**Comment by chrissi55** [comment]
Hi there,

since a few weeks matrix has rolled out the simplified sliding sync method to matrix-synapse.
Can anybody here give me a link or a hint how to configure *.yaml / .well-known files for enabling simplified sync in latest matrix-synapse?

At the moment i use a parallel docker file for having sliding_sync support at my (family- / homeserver) but i like to know what steps to reproduce to switch from synapse + docker (ssync) to just one synapse simplified sync system.

Thanks in advance!

**Comment by spaetz** [comment]
It is enabled by default since 1.114

**Comment by chrissi55** [comment]
So i will have to edit my /.well-known file(s) and delete the (previous nescessary) entries for my sliding sync proxy in docker?

In my nginx reverse proxy also changes were made like

```
    location ~ ^/(client/|_matrix/client/unstable/org.matrix.msc3575/sync) {
		proxy_pass http://192.168.55.99:8009;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Host $host;
	}
```
What about these settings?
