### ISSUE TITLE
Can't sync large account in sliding-sync

### ISSUE THREAD

**Issue by catfromplan9** [matrix-org/sliding-sync#29]
Log:

WRN Poller: sync v2 poll returned temporary error error="DoSyncV2: request failed: Get \"https://server.org/_matrix/client/r0/sync?timeout=0&filter=%7B%22room%22%3A%7B%22timeline%22%3A%7B%22limit%22%3A1%7D%7D%7D\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" code=0 user_id=@user:server.org

**Comment by catfromplan9** [comment]
On /client/ page on site error is after a while: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Does not happen with other account

Also need clarification, do I need to visit /client/ on the sync page and put in token for each account I want to use sliding sync or is this to only be used once? Is the sliding sync option in .well-known supported in element web and mobile?

**Comment by kegsay** [comment]
The proxy will time out upstream requests to the homeserver after a while, which is what "Client.Timeout exceeded while awaiting headers" is. This means the account is so big that it can't get a sync v2 response. It will keep trying to get this response so it can get the data for your account.

The /client/ page is just for testing, and isn't required if you're using another sliding sync client like Element Web or Element X.

**Comment by kegsay** [comment]
No actionable stuff here.

**Comment by catfromplan9** [comment]
> The proxy will time out upstream requests to the homeserver after a while, which is what "Client.Timeout exceeded while awaiting headers" is. This means the account is so big that it can't get a sync v2 response. It will keep trying to get this response so it can get the data for your account.
> 
> The /client/ page is just for testing, and isn't required if you're using another sliding sync client like Element Web or Element X.

So this will not be an issue?

**Comment by lephisto** [comment]
Same issue here. Can't sync my large account, which works fine with legacy matrix. I already tidied up old "Empty Rooms", but it's like 50 personal rooms, and 80-100 public rooms. Where to start?
