### ISSUE TITLE
txn IDs: can be unset when /sync poller lags

### ISSUE THREAD

**Issue by kegsay** [matrix-org/sliding-sync#3]
If Alice and Bob are in a room, and Alice sends a message, we want to make sure that the event we pass to the client include the `transaction_id` she sent. However, Bob may get that event first down his v2 poller, meaning the database won't include that value. We fixed this in https://github.com/matrix-org/sliding-sync/commit/2920191a446f4ebbfb770ff89d67c34d0eccb1d1 to have a transaction ID cache which will inject the right transaction ID for the right user.

HOWEVER... if Alice's sync stream is lagging very badly, we may not have got the `transaction_id` by the time she does a `/sync` request. In this case, what should we do?
 - Not send the event and propagate the upstream lag?
 - Send the event but without a transaction ID?

We choose the latter, but this means that under certain circumstances we will fail to send a transaction ID with an event. This is a proxy limitation, and actual server implementations of sliding sync don't have this problem.

**Comment by ara4n** [comment]
just commenting to say that this causes duplicated echo on clients (c.f. https://github.com/vector-im/element-x-ios/issues/939), so i can find it in future.

@kegsay: presumably the workaround for this is to route /send via the proxy so it can tally up the txns correctly? We can't ship EX with it in the current state.

**Comment by kegsay** [comment]
Persistent duplicate events is a client-side bug, as the event ID should be used to pair up as a fallback. Flickering ephemeral duplicate events are indeed this issue.

The reason why is because:
 - if /send returns first, then we see the event ID in /sync => dedupe.
 - if /sync returns first, we dupe the message, then /send returns with the event ID => dedupe.

**Comment by ara4n** [comment]
my hunch would be to go for "wait for the TID from the HS", as surely for the common case it wouldn't slow things down - it'd just slow things down for the edge case where the race has happened?

**Comment by kegsay** [comment]
> my hunch would be to go for "wait for the TID from the HS", as surely for the common case it wouldn't slow things down - it'd just slow things down for the edge case where the race has happened?

It depends on the lag time of individual synchrotrons e.g on matrix.org. This can be 10s of seconds. Worst case, the delay is the total latency between the fastest (which sees the msg first without a txn ID) and slowest synchrotrons (which finally sees the txn ID).

There is a third option, which is to resend the event when we realise that the event was supposed to have a txn ID. This post-fixup would provide the best of both worlds:
 - it keeps latency as low as possible on the proxy.
 - it allows clients to de-dupe without causing flickering local echo, but only if they also de-dupe on event ID.

It's not _uncommon_ for SS to send duplicate timeline events, particularly given the lack of delta tokens in the proxy currently, however this is relying on clients saying `ON CONFLICT REPLACE` rather than `ON CONFLICT DO NOTHING`. The former will cause more disk I/O as we are constantly rewriting events to disk, unless the client is intelligent and only does this if `unsigned.transaction_id` is present. An outstanding Q to this solution would be how to handle scenarios where the event with the transaction ID was NOT the most recent event - are we forced into resending the complete set of events?

**Comment by kegsay** [comment]
Unfortunately, the "intercept /send" solution also doesn't work because of the following failure mode:
 - Alice /send txn=A to the proxy.
 - Proxy remembers Alice, Room ID, txn=A.
 - Proxy forwards /send to the HS.
 - HS processes and sends remote echo event ID = $B.
 - Proxy sees remote echo $B on a different poller, Bob.
 - Proxy INSERTs $B and notifies downstream.
 - Alice's SS conn sees $B and returns it, DUPLICATE!
 - Proxy /send 200 OKs with $B.
 - RUH ROH

Basically, the same failure mode can happen to the proxy as it can to the client.

The "wait for the txn ID" solution has serious shortcomings because in order to do this consistently we would need all pollers to emit all last seen NIDs for each room for each poller (device). In practice, this means ballooning traffic for events from 1 to N (where N=number of devices in the same room). This massively hurts scalability.

A better solution hashed out with @DMRobertson was to instead have a grace period with an "all clear" pubsub message. It'll work like this:
 - When the poller sees an event with a txn ID, send a new pubsub message `V2EventWithTransactionID` or something, containing the event ID, txn ID, room ID, user ID.
 - When the poller sees an event, check the sender field. If the poller is tracking that sender, keep an in-memory map that this poller has seen this event. When all devices for that sender have seen this event, send an `V2EventWithTransactionID` with a value of "no transaction" - every device saw the event but there was no txn id ergo it was sent by a non-SS client.
 - When the subscriber sees a new event from pubsub, ask the following:
    * Check the sender. Is this sender currently syncing? NO: continue as normal. YES...
    * Start tarpitting events for this user, with a timeout of N seconds.
    * New events get tarpitted.
    * When recv a `V2EventWithTransactionID`, check if the event ID matches the tarpitted event. If match, untarpit and deliver to ConnState.

This has the following caveats:
 - If the event-with-txn-id arrives after N seconds, it will cause a local echo flicker.
 - Client-sent events will tarpit their own traffic until all pollers see the remote echo, or until N seconds is reached. You could self-DoS yourself if you regularly send events with a period < N seconds.
    * this could be mitigated by untarpitting batches of the queue, releasing events up to the acknowledged event, but it's not clear we need this.

The benefit to doing this is that worst case we only emit 1 extra pubsub message, so O(2) per event. Critically, it doesn't scale on the # devices.

**Comment by kegsay** [comment]
Impl notes:
 - Have a separate file+struct to do this, similar to https://github.com/matrix-org/sliding-sync/blob/main/sync3/handler/rooms_builder.go - easy to add UTs
 - This struct consumes from the live updates channel https://github.com/matrix-org/sliding-sync/blob/main/sync3/handler/connstate_live.go#L26 so we don't need any extra locking.
 - It needs some information from the conn ([roomSubscriptions](https://github.com/matrix-org/sliding-sync/blob/main/sync3/handler/connstate.go#L31) to see if there is a room subscription for this event? That doesn't cover list windows though...)
 - For each update, it asks:
    * Is it a room event update?
    * Is the sender of this event my connection's user ID?
    * Is this room being tracked / subscribed to?
    * If all the above are YES, shove it into a queue bucketed by room ID. Else, proxy the update through to connStateLive.
 - For each queued update:
    * Wait up to $timeout seconds, after which time release everything up to and including the event.
    * Terminate the timeout early if there is a `V2TransactionID` for this event/user/room, either with a transaction ID or with an "all clear" no txn ID. The txn ID itself doesn't need to be added to the update, as we call AnnotateWithTransactionIDs later https://github.com/matrix-org/sliding-sync/blob/3a17ec0c72d19156a87011155e6d9dca80835be2/sync3/handler/connstate_live.go#L178
