### ISSUE TITLE
Pre-built release images for arm64

### ISSUE THREAD

**Issue by spantaleev** [matrix-org/sliding-sync#31]
It looks like the current latest release ([v0.99.1](https://github.com/matrix-org/sliding-sync/releases/tag/v0.99.1)) is only available for `amd64`, not for `arm64`.

Only `:latest` seems to be available for `arm64`.

I suppose a new release hasn't been done since multi-arch support was added to CI. Perhaps it's time for a new stable release soon?

**Comment by DMRobertson** [comment]
I think these images should exist today. On https://github.com/matrix-org/sliding-sync/pkgs/container/sliding-sync/109065727?tag=v0.99.4 I see

![image](https://github.com/matrix-org/sliding-sync/assets/8614563/a104117a-0417-4c84-ab16-a4a6d9ab37b7)

which has an ARM64 entry.

If something's not working, do reopen or let us know and we can take a look.
