### ISSUE TITLE
Still having "Server not supported"

### ISSUE THREAD

**Issue by xaionaro** [matrix-org/sliding-sync#315]
I've setup the sliding server for a matrix server, but "Element X" still says "Server not supported" and "This server currently doesn't support sliding sync". It does not give any sane error I can act on, so I have no idea what's wrong. Any ideas how to debug? Asking here, since the button "Learn more" of the error window leads to the landing page in this repository.

**Comment by DMRobertson** [comment]
You probably need to declare where the proxy is running in your client well-known file: see https://github.com/matrix-org/sliding-sync#setup.

<blockquote>
In both cases, the path https://example.com/.well-known/matrix/client must return a JSON with at least the following contents:

```json
{
    "m.homeserver": {
        "base_url": "https://example.com"
    },
    "org.matrix.msc3575.proxy": {
        "url": "https://syncv3.example.com"
    }
}
```
</blockquote>

**Comment by wuzhongyi1105** [comment]
Well I use Delegation which is a Matrix feature, my user names look like @user:example.com, the path https://example.com/.well-known/matrix/client return a JSON with at least the following contents: 

```
{
    "m.homeserver": {
        "base_url": "https://matrix.example.com"
    },
}
```

And now, the path https://example.com/.well-known/matrix/client must return a JSON with at least the following contents:

```
{
    "m.homeserver": {
        "base_url": "https://matrix.example.com"
    },
    "org.matrix.msc3575.proxy": {
        "url": "https://matrix.example.com"
    }
}
```

BUT "Element X" still says "Server not supported" and "This server currently doesn't support sliding sync". 

slilding-sync with synapse host on same hostname, the `matrix.example.com` nginx configuration like this:

```
listen 443 ssl;

location ~ ^/(client/|_matrix/client/unstable/org.matrix.msc3575/sync) {
    proxy_pass http://localhost:8009;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
}

location ~ ^(\/_matrix|\/_synapse\/client) {
    proxy_pass http://localhost:8008;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
}
```
and the `example.com` nginx configuration like this:
```

    listen 443 ssl;

    location /.well-known/matrix/client {
        return 200 '{"m.homeserver": {"base_url": "matrix.example.com"},"org.matrix.msc3575.proxy": {"url": "matrix.example.com"}}';
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
    }

    location /.well-known/matrix/server {
        return 200 '{"m.server": "matrix.example.com:443"}';
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
    }
```

**Comment by DMRobertson** [comment]
> And now, the path [example.com/.well-known/matrix/client](https://example.com/.well-known/matrix/client) return a JSON with the following contents:

This looks sensible and agrees with what https://matrix.org/.well-known/matrix/client serves (which also uses delegation).


> and the `example.com` nginx configuration like this:

The matrix/client response defined here lacks protocols (no `https` in the urls). I would try adding those.

I would also try looking at nginx logs to see if there is evidence of Element X making requests to the well known endpoint.

For more advice, I suggest asking in the [Sliding Sync Discussion room](https://matrix.to/#/#sliding-sync:matrix.org), the [Element X iOS](https://matrix.to/#/#element-x-ios:matrix.org) or [Element X Android](https://matrix.to/#/#element-x-android:matrix.org) rooms.

**Comment by xaionaro** [comment]
After some experiments and resetupping from scratch I managed to setup my instance. But I still believe there should be a better error message (for example an error code include, which is google-able to a specific problem).

**Comment by DMRobertson** [comment]
> But after some experiments and resetupping from scratch I managed to setup my instance.

Did you identify what the issue was?

> But I still believe there should be a better error message (for example an error code include, which is google-able to a specific problem).

Agreed. Please could you raise an issue for this against the Element X client repo?

**Comment by xaionaro** [comment]
> Did you identify what the issue was?

I think I did some false assumption about `"m.homeserver"` is not needed if I use the same domain name or something like that.

**Comment by DMRobertson** [comment]
Fair enough. In any case, I'm glad you got it working!
