### ISSUE TITLE
EW: Searching for a room that doesn't exist returns huge numbers of recents & unrelated room results

### ISSUE THREAD

**Issue by ara4n** [matrix-org/sliding-sync#32]
Search in unified search for some gibberish like azhxhsdcue.  Observe that you have a huge number (20?) of recent rooms returned as results - as well as loads (20?) of rooms which don't match either.

Without SS, EW returns zero results, as you'd expect.

**Comment by kegsay** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/8328/commits/cda609dc58e452297a0d04f134052bea40c78e7d
