### ISSUE TITLE
WebUI - getting 405

### ISSUE THREAD

**Issue by floviolleau** [matrix-org/sliding-sync#320]
Hi,

I'm self hosted.

When I'm using web ui, I'm getting 405 response after using my private access token.
`{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}`

Despite having a working "classic" sync with release clients.

What should I do?

**Comment by kegsay** [comment]
There is no web UI for the proxy. The `/client/` test rig is only exposed for development purposes and isn't included in the final Docker image.

**Comment by floviolleau** [comment]
OK. I'm not using Docker and I don't have any clues to make it working with the new Android app.

**Comment by DMRobertson** [comment]
> I don't have any clues to make it working with the new Android app.

The first place to look for clues is the sliding sync proxy logs. Can you see any error messages or warnings? Can you see evidence of your android device trying to connect?

For further advice and support, please ask in the [Sliding Sync Discussion room](https://matrix.to/#/#sliding-sync:matrix.org).

**Comment by floviolleau** [comment]
I successfully made it by using this apache config

```apache
RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
ProxyRequests Off
ProxyPreservehost on

ProxyPass /_matrix/client/unstable/org.matrix.msc3575/sync http://127.0.0.1:8009/_matrix/client/unstable/org.matrix.msc3575/sync
ProxyPassReverse /_matrix/client/unstable/org.matrix.msc3575/sync http://127.0.0.1:8009/_matrix/client/unstable/org.matrix.msc3575/sync
ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix
ProxyPass /_synapse http://127.0.0.1:8008/_synapse nocanon
ProxyPassReverse /_synapse http://127.0.0.1:8008/_synapse
```
