### ISSUE TITLE
Walk over tombstones to derive the correct space children

### ISSUE THREAD

**Issue by ara4n** [matrix-org/sliding-sync#33]
On SS, a space like 'Working @ Element' has 6 rooms and zero People.

On non-SS, it has 10 rooms (of which 2 are favourite) and about 30 People.

**Comment by kegsay** [comment]
The People section will be incorrect regardless due to SS ignoring the "filter DMs by members of this Space". The room section however should be accurate.

**Comment by kegsay** [comment]
I suspect the room section is not accurate due to the lack of walking over tombstones. Will check.

**Comment by kegsay** [comment]
Seems to be the case, awaiting confirmation.

**Comment by kegsay** [comment]
It is.

**Comment by kegsay** [comment]
This is now MSCed as `resolve_tombstones: true|false`.

**Comment by kegsay** [comment]
Needed for DM maps, space children, anything else?

**Comment by kegsay** [comment]
This is now resolved with `include_old_rooms` and relying on clients to walk over tombstones.
