### ISSUE TITLE
Release build artifacts on releases

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/sliding-sync#334]
This proxy is required for upcoming ElementX. Make it easier for the community to use the proxy in the future:

- Release go build artifacts when tagging releases

It seems possible: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

**Comment by DMRobertson** [comment]
As well as #339 I fixed this up in 697ac7a0626989313e6920fd7a1603af25c2e79f...2b0f63d784c536cebca5bba8803dd314b70fa767. I have been testing this with unpublished draft releases. Very  very terse instructions at https://github.com/matrix-org/sliding-sync/blob/3b14c056c85f6bb2b5c437a0bf725eb363d5cf20/RELEASING.md, but TL;DR you create and push a tag starting with `v`, which drafts a release for you.

@kegsay suggest you try this out to see if you're happy with this.
