### ISSUE TITLE
postgres connection refused

### ISSUE THREAD

**Issue by ewof** [matrix-org/sliding-sync#376]
`psql postgres://debian:passwordhere@127.0.0.1:5432/syncv3` i can connect fine

`sudo docker run --rm -e "SYNCV3_SERVER=https://matrix.domain.com" -e "SYNCV3_SECRET=$(cat .secret)" -e "SYNCV3_BINDADDR=:8009 SYNCV3_TLS_CERT=/etc/l
etsencrypt/live/matrix.domain.com/fullchain.pem SYNCV3_TLS_KEY=/etc/letsencrypt/live/matrix.domain.com/privkey.pem" -e "SYNCV3_DB=postgres://debian:passwordhere@127.0.0.1:5432/syncv3 sslmode=
disable" -p 8009:8009 ghcr.io/matrix-org/sliding-sync:latest`

OR
`sudo docker run --rm -e "SYNCV3_SERVER=https://matrix.domain.com" -e "SYNCV3_SECRET=$(cat .secret)" -e "SYNCV3_BINDADDR=:8009" -e "SYNCV3_DB[0/1651]
bian dbname=syncv3 sslmode=disable host=127.0.0.1 password='autism'" -p 8009:8009 ghcr.io/matrix-org/sliding-sync:latest` (with out without ssl-mode=disable makes no difference)

i get
`panic: dial tcp 127.0.0.1:5432: connect: connection refused`

using `host.docker.internal` gives me "no such host"
it works with `network="host"` but then the ports aren't published

**Comment by ewof** [comment]
doing
<img width="666" alt="image" src="https://github.com/matrix-org/sliding-sync/assets/26354814/dd41bf3d-6c19-4d4d-b488-0a6ec4659d34">

and using `sudo docker run --add-host host.docker.internal:host-gateway --rm -e "SYNCV3_SERVER=https://matrix.domain.com" -e "SYNCV3_SEC[0/1856]t .secret)" -e "SYNCV3_BINDADDR=:8009" -e "SYNCV3_DB=postgres://postgres:passwordhere@host.docker.internal:5432/syncv3" -p 8009:8009 ghcr.io/matrix-org/sliding-sync:latest`

**Comment by dran1x** [comment]
How did you solve this?

**Comment by ewof** [comment]
the command in my nov 10th comment and editing pg_hba.conf
`sudo docker run --add-host host.docker.internal:host-gateway --rm -e "SYNCV3_SERVER=https://matrix.domain.com" -e "SYNCV3_SECRET=$(cat .secret)" -e
"SYNCV3_BINDADDR=:8009" -e "SYNCV3_DB=user=postgres dbname=syncv3 sslmode=disable host=host.docker.internal password='password'" -p 8009:8009 ghcr.io/matrix-org/sliding-sync
:latest`

realized the command is fucked it has the [0/1856] from my tmux
