### ISSUE TITLE
DM room name updates to wrong name

### ISSUE THREAD

**Issue by gnunicorn** [matrix-org/sliding-sync#38]
**Describe the bug**
On updates the name of DM rooms updates to `Other and Me` (rather than `Other` as it was previously sent and is correct according to spec). 

**To Reproduce**
On ROSA, after fetching the rooms list, we subscribe to the set of rooms we have in view (as we want to show the latest room message and additional avatar requests). Now send a new message in a DM you've subscribed to and you'll see that the response from the proxy contains an update for `name` that is incorrect.

**Comment by gnunicorn** [comment]
Sorry, my example wasn't clear. should have been `$OTHER`, and `$OTHER and $ME` . They are existing DMs, all invited, chatting for a while already. According to spec they should just show the name of the other person and at first sync they do. But on an update they are changed to them and my name.
 
- What were the previous room names for this room?
  Seen this twice for the user stefan with: `Ben` switching to `Ben and Stefan`, but also `Doug` switching to `Doug and Stefan`.   
- What is the display name of all users in this room?
  In this case `Stefan` and then the DM is either with `Ben` or with `Doug` respectively. 
- What is the membership states of all users in this room?
  They have all joined.

**Comment by kegsay** [comment]
Right, it sounds like the `name` field in the `UserRoomMetadata` is not removing the user ID of the connection in the heroes list, causing it to calculate it incorrectly like this.

**Comment by kegsay** [comment]
https://github.com/matrix-org/sliding-sync/commit/f4a52001507ed858552f954b5b557490addd7e49
