### ISSUE TITLE
Does the "Database string" support to set port?

### ISSUE THREAD

**Issue by Curious-r** [matrix-org/sliding-sync#381]
The documentation does not mention this.
`SYNCV3_DB="user=$(whoami) dbname=syncv3 sslmode=disable host=host.docker.internal port=5432 password='DATABASE_PASSWORD_HERE'`
Is this the right way?

**Comment by Curious-r** [comment]
Seems works, in my currently test.

**Comment by DMRobertson** [comment]
Per the README and help message:

> ```
> SYNCV3_DB         Required. The postgres connection string: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
> ```

Please see the postgres docs (for the version of postgres that you're running) for full details. In particular see https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS for the list of keyword-value pairs accepted by this syntax.

For any other questions regarding deployment, please consider asking in the [Sliding Sync Discussion](https://matrix.to/#/#sliding-sync:matrix.org) room before opening an issue.
