### ISSUE TITLE
SYNCV3_BINDADDR variable for unix socket

### ISSUE THREAD

**Issue by MrSpadduzza** [matrix-org/sliding-sync#383]
Could you elaborate about this, please?
SYNCV3_BINDADDR   Default: 0.0.0.0:8008. **The interface and port to listen on. (Supports unix socket: /path/to/socket)**

I have tried various syntax versions, but I keep getting the following error:
listening on unix://etc/matrix-synapse/sliding-sync-0.99.12/
failed to listen and serve error="listen tcp: lookup tcp///etc/matrix-synapse/sliding-sync-0.99.12/: Servname not supported for ai_socktype"

The first line, where it declare the path vary according to the variable, but the second line error is always the same.

The error changes, if I omit 'unix:' from the variable path:
listening on /etc/matrix-synapse/sliding-sync-0.99.12/syncv3.socket
failed to listen and serve error="listen tcp: address /etc/matrix-synapse/sliding-sync-0.99.12/syncv3.socket: missing port in address"

I have tried with or without socket file name; the socket file does not exist and the locations user owner is the same that runs the proxy.

Any idea?

**Comment by DMRobertson** [comment]
See https://github.com/matrix-org/sliding-sync/releases/tag/v0.99.13. Please try again with the latest release!

**Comment by MrSpadduzza** [comment]
Thank you very much for your quick reply!! I'm trying it now and get back

**Comment by MrSpadduzza** [comment]
I confirm the proxy started happily with SYNCV3_BINDADDR and SYNCV3_SERVER variables set as =/path/to/socket/file
I'll go on with some testing.
Thanks again!!
