### ISSUE TITLE
Can we adverstise the proxy entry in our homeserver.yml instead of /.well-known/matrix/client

### ISSUE THREAD

**Issue by Domoel** [matrix-org/sliding-sync#404]
Hi,

I am running my synapse installation in a docker environment and cannot access the "/.well-known/matrix/client" file to make the necessary adjustments to advertise the proxy entry. Instead I asked myself if we can bypass this by making some adjustments to the homeserver.yml.

Synapse does support for these kind of options with the following config command: 

serve_server_wellknown: true
well_known_server_config:
  server: "DOMAIN.ltd"
well_known_client_config:
  client: "DOMAIN.ltd"

Is there something similiar for the following entry which usually must be put into the proxy config?

{
    "org.matrix.msc3575.proxy": {
        "url": "https://slidingsync.proxy.url.here"
    }
}

And if not how can I get access to the "/.well-known/matrix/client"" config within a docker container (running on a Synology NAS with container manager)?

Thanks for helping me out. I'm really not an expert (learning by doing). So advise would be highly appreciated.

Best
Dom

**Comment by Slug-V** [comment]
homeserver.yml has a preference `extra_well_known_client_content`:

```yaml
extra_well_known_client_content:
  org.matrix.msc3575.proxy:
    url: "https://slidingsync.proxy.url.here"
```

My instance uses this.

**Comment by Domoel** [comment]
Thank you! this was the solution I was looking for! Is this part of the official documentation? If so where to find it?

**Comment by Slug-V** [comment]
You're welcome👍
I found this below.
<https://element-hq.github.io/synapse/v1.99/usage/configuration/config_documentation.html#extra_well_known_client_content>

The example doesn't have the 2-level setting, but it has no problem.
This will be documented for all Synapse users.

**Comment by Richigeht** [comment]
> You're welcome👍 I found this below. https://element-hq.github.io/synapse/v1.99/usage/configuration/config_documentation.html#extra_well_known_client_content
> 
> The example doesn't have the 2-level setting, but it has no problem. This will be documented for all Synapse users.

Where did the documentation go? I haven't seen it - only found this just now through digging (and trying to find out, why my slinding sync isnt working)

**Comment by Slug-V** [comment]
@Richigeht I'm sorry, I chose wrong word😝

> This will be documented

What I mean is "This SHOULD be documented (by someone)", and no one there.
So I created a PR.
