### ISSUE TITLE
panic: SSL is not enabled on the server

### ISSUE THREAD

**Issue by llessi06** [matrix-org/sliding-sync#408]
I want to add Sliding-Sync to my Matrix Server because the new Element Client is complaining that I need it to function, but now the sliding-sync service is constantly restarts with the following error:

goroutine 1 [running]:
github.com/jmoiron/sqlx.MustExec(...)
        github.com/jmoiron/sqlx@v1.3.3/sqlx.go:722
github.com/jmoiron/sqlx.(*DB).MustExec(0xc00051f988?, {0xdc5808?, 0xc00051f988?}, {0x0?, 0xc00051f901?, 0xc00051f9d8?})
        github.com/jmoiron/sqlx@v1.3.3/sqlx.go:366 +0x46
github.com/matrix-org/sliding-sync/state.NewRoomsTable(...)
        github.com/matrix-org/sliding-sync/state/rooms_table.go:24
github.com/matrix-org/sliding-sync/state.NewStorageWithDB(0xc0001ccb40, 0x8?)
        github.com/matrix-org/sliding-sync/state/storage.go:86 +0x38
github.com/matrix-org/sliding-sync.Setup({0xc00003e00e, 0x22}, {0xc00004005a, 0x39}, {0xc00004202e, 0xb}, {0x0, 0x0, 0x0, 0x3b9aca00, ...})
        github.com/matrix-org/sliding-sync/v3.go:117 +0x212
main.main()
        github.com/matrix-org/sliding-sync/cmd/syncv3/main.go:213 +0x175b
Sync v3 [0.99.15] (bbb886e)
Debug=false LogLevel= MaxConns=0
panic: pq: SSL is not enabled on the server

What is the problem ?

**Comment by kegsay** [comment]
Your postgres URI/connection string is missing `sslmode=disable`. It defaults to on.

**Comment by llessi06** [comment]
Thanks that was the Problem.

**Comment by Germimi2** [comment]
> Thanks that was the Problem.

Na Eh
