### ISSUE TITLE
stub client at /client/ not available - leads to 404

### ISSUE THREAD

**Issue by mpsd** [matrix-org/sliding-sync#409]
While trying to debug a non-working installation of sliding-sync proxy I tried to connect with stub client as described in installaton doc ( http://localhost:8008/client/ ) but this leads to 404. /client/server.json exists however I cant manage to use sliding sync with my existing and working homeserver and element X on android.

I tried both - using the supplied binary for Linux from release page and compiling from source by my own. 404 is the same on both.

**Comment by mpsd** [comment]
Forgot to mention - I can see the request been routed correctly to syncv3 as the console on my server is reporting the 404 too.

**Comment by kegsay** [comment]
`/client/` is a debug test client, and is not included in the final Dockerfile. To get it included you need to build the binary from source via `go build`.

I can confirm that building and running the binary then hitting `http://localhost:8008/client/` (with trailing slash!) works correctly and renders the test client. Double check that the bind port on sliding sync is in fact 8008 and you didn't change it to not port conflict with Synapse.

**Comment by mpsd** [comment]
Thank you for this clarification. I've built the binary from source with 'go build' but I changed the binding port which seems to cause the issue.
