### ISSUE TITLE
Expand extensions to allow them to be registered on a specific named list(s)

### ISSUE THREAD

**Issue by kegsay** [matrix-org/sliding-sync#41]
This is so background spider lists don’t get to-device messages / typing / receipts / account data. - We can do this now because key-based lists are landed. This is useful for EX because the “all rooms” list we don’t want typing notifs / receipts / etc, but we do in the “visible rooms” list, and atm you can’t express that.

SITREP:

- [x] typing #50
- [x] account data #53
- [x] receipts #54
- [ ] todevice
- [x] e2ee: N/A. None of the information communicated by this extension is scoped to a particular room.

**Comment by DMRobertson** [comment]
Are you envisioning this as something that each extension opts into, or a mechanism baked into the MSC (e.g. a mandatory `lists` key reserved by the spec within each extension's parameter object)?

> This is useful for EX because the “all rooms” list we don’t want typing notifs / receipts / etc, but we do in the “visible rooms” list, and atm you can’t express that.

Do we have a similar situation with the Room Subscriptions API? Is it useful for EX to subscript to a room but e.g. opt out of typing notifications for that room?

**Comment by kegsay** [comment]
> (e.g. a mandatory lists key reserved by the spec within each extension's parameter object)?

Yes, this. It would be useful to have a single way to express "this extension applies to these named lists and these named room IDs". This single way could just be a naming convention e.g every extension can say `lists: [ "foo" ,"bar" ]` and `rooms: ["!foo", "!bar"]` .

> Do we have a similar situation with the Room Subscriptions API? Is it useful for EX to subscript to a room but e.g. opt out of typing notifications for that room?

Potentially, yes.

I'm unsure on the best name for the key. In essence, the values represent the overall scope of that extension, and its omission will catch all lists/rooms on the user's account. It's important not to imply it's returning room events because in some cases it might not be (e.g the to-device extension doesn't have room events so you might think this is pointless, but it's actually useful in the future if we want to say only deliver to-device events for users who are in these rooms given by these lists. The values can be either a room ID or a list key. It's _probably_ safe to mux them together given list keys shouldn't start with a `!`, and you're only confusing yourself if you name a list after a room ID.  Maybe it's good enough to just have it be: `scope: [ "list_a", "list_b", "!roomA, "!roomB" ]` ?

**Comment by DMRobertson** [comment]
> I'll write something down on the MSC and see how it goes.

[matrix-org/matrix-spec-proposals@`602d342` (#3575)](https://github.com/matrix-org/matrix-spec-proposals/pull/3575/commits/602d342cc4210c015a13a4a2b0fc73929d444b8e)

**Comment by DMRobertson** [comment]
We consider this good enough for now; we can revisit the to-device extension in the future.

**Comment by kegsay** [comment]
Closing this, let's have a different issue for to-device stuff. The to-device stuff isn't needed for a v1.
