### ISSUE TITLE
Misleading log configuration

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/sliding-sync#411]
I can see two switches for configure logging:

`SYNCV3_DEBUG` and `SYNCV3_LOG_LEVEL`.

`SYNCV3_DEBUG` is `trace` level:
https://github.com/matrix-org/sliding-sync/blob/8750e1c4359bc3743e799df9fc3b97b12f2d1fa3/cmd/syncv3/main.go#L176-L177

Is `SYNCV3_DEBUG` the old an "deprecated" one?

It was introduced in:
- #99

**Comment by kegsay** [comment]
SYNCV3_DEBUG should only be used by developers. Setting it turns on trace logging but it also makes failed assertions panic, so you'll see more crashes if you enable it.
