### ISSUE TITLE
Room account data can be spammed with duplicates

### ISSUE THREAD

**Issue by kegsay** [matrix-org/sliding-sync#417]
Reported by @bnjbvr 

I think the account data extension can send room account data multiple times redundantly when catching up on a nearly full buffer. E.g if you have 100 items for the same room in the buffer, the account data extension pulls the room account data 100 times and appends it to the response.

Close when this has a test showing it can't happen / can happen and bug is fixed.

EDIT: seen a mitmdump which shows this. Sporadic room account data are duplicated 3,8,N times. Hypothesis: If you SYNC a bunch of rooms whilst there are RoomUpdate items in the buffer, it will cause duplicates.

**Comment by ara4n** [comment]
(this caused https://github.com/element-hq/element-x-ios/issues/2650)
