### ISSUE TITLE
Sliding Sync proxy returns a computed room name instead of the value of `m.room.name` when it is requested.

### ISSUE THREAD

**Issue by bmarty** [matrix-org/sliding-sync#434]
The Rust SDK is requesting the value of `m.room.name` (@bnjbvr may give a pointer on this) but the returned value seems to be a computed room name, like `Alice, Bob and 3 others`.

**Comment by bnjbvr** [comment]
I just checked, and the name we're using is the `name` field in the `room` subpart of a sliding sync response, which seems to contain computed data.

**Comment by kegsay** [comment]
`room.name` contains computed data as per MSC3575. If you want the raw value for `m.room.name` you need to request it in `required_state`.

**Comment by bnjbvr** [comment]
Oh so it's the SDK doing something wrong. Thanks.
