### ISSUE TITLE
perf: refactor device data table

### ISSUE THREAD

**Issue by kegsay** [matrix-org/sliding-sync#435]
The device data table doesn't play well with the MVCC nature of postgres because that table has relatively few but huge rows. Each update is therefore expensive, as it contains a copy of the old state. As the rows aren't being touched frequently enough, it doesn't tend to get detected by the AUTOVACUUM daemon, causing excessive disk usage. This is exacerbated by the nature of the data: a 1:N mapping per unit work (one device logging in results in N updates).

This should be refactored into a new `syncv3_device_list_updates` table which would look something like:
```
user_id | device_id | target_user_id | target_state | bucket
--------+-----------+----------------+--------------+--------
alice   |  FOOBAR   |     bob        |    changed   |    new
alice   |  FOOBAR   |     charlie    |    left      |    new
alice   |  FOOBAR   |     bob        |    left      |    sent

UNIQUE(user_id, device_id, target_user_id, bucket)

new/sent and changed/left will likely be enums.
```
This says, for the client alice|FOOBAR:
 - We sent bob=left and have not got an ACK yet for it
 - We have new changes bob=changed, charlie=left and have not sent it to the client yet.

When the poller gets even more device list updates, it just UPSERTs the value e.g `doris, changed` with bucket=new.

When the client requests device lists, we:
 - Atomically... `begin txn`
 - Delete the now acknowledged changes `delete where user_id=alice, device_id=FOOBAR, bucket=sent`
 - Grab any new updates `select target_user_id, target_state where user_id=alice, device_id=FOOBAR, bucket=new`
 - Mark those updates as sent `update set bucket=sent where user_id=alice, device_id=FOOBAR, bucket=new`
 - `COMMIT`

This means a device list change only results in a single UPSERT, whereas today it involves a deserialisation/serialisation step which is expensive.

This should:
 - reduce poller CPU usage
 - reduce DB load
 - reduce the size of dead tuples
 - increase churn on this new table: however we expect postgres to cope much better with frequently inserted/updated/deleted small rows.

Critically, for the pathological scenario of a client who has gone away never to return, their cost on the DB is much smaller as we are not accumulating an ever growing blob of CBOR.

**Comment by devonh** [comment]
This makes sense to me as an optimization for device list updates.
What will happen with the other device data fields such as one-time keys & fallback keys?
Will those still be in the device data table as a CBOR blob, and just the device list info will be extracted out into it's own table?

**Comment by S7evinK** [comment]
Assuming 
>  Mark those updates as sent `update set bucket=sent where user_id=alice, device_id=FOOBAR, bucket=new`

is a C&P error and should be `bucket=sent`, looks sane to me as well.
Like for the `syncv3_device_data`, we probably should set a `fillfactor` for the table, as otherwise Postgres needs to update the index on every upsert.

**Comment by kegsay** [comment]
No I meant what I wrote. The point is to swap new for sent in a transaction.

**Comment by S7evinK** [comment]
Err.. Yes, I read that query wrong.
