### ISSUE TITLE
Issue with SSO

### ISSUE THREAD

**Issue by PaulaBras** [matrix-org/sliding-sync#453]
Hi, I am just building Matrix with Sliding Sync. I use Synapse with Authentik SSO. Is it possible to make it work in combination with sliding Sync and then Element X?

The Issue I am having is that Element X is finding the .well-known but just displaying me a user login prompt. What am I doing wrong?

Thanks in advance.

**Comment by kegsay** [comment]
You can't register for an account with Element X yet as far as I know. You can only login. And it only supports basic password login or matrix-authentication-service SSO, not the SS built into Synapse.

**Comment by PaulaBras** [comment]
I don't think we meant the same thing.
ok in Synapse the SSO works fine, also in Element. But with Sliding Sync Element X doent give me the option for the SSO link.
