### ISSUE TITLE
refactor: metadata struct names

### ISSUE THREAD

**Issue by kegsay** [matrix-org/sliding-sync#46]
There's 3 tiers, all with bad names:
 - Global: `internal.RoomMetadata`
 - User `caches.UserRoomData`
 - Connection `sync3.RoomConnMetadata`

This isn't clear enough.

**Comment by DMRobertson** [comment]
I think part of the confusion is that the RoomConnMetadata holds a copy of the other two structs, but uses them for different purposes. (E.g. LastMessageTimestamp)

**Comment by DMRobertson** [comment]
I think it would also help if we had a type `caches.GlobalRoomMetadata`. ATM the RoomConnMetadata embeds `internal.RoomMetadata` but edits it in place for its own purposes, which is confusing.

**Comment by kegsay** [comment]
`RoomConnMetadata` contains copies of the user/global cache entries for that room _at the point in time the event in question was received_, which is useful for pulling out e.g the room name at that event.

**Comment by DMRobertson** [comment]
Hmm. How do you find this wording?

> RoomConnMetadata keeps a copy of the global and user cache data, updated whenever we have an event to report to that conn.
