### ISSUE TITLE
perf: startup times too slow

### ISSUE THREAD

**Issue by kegsay** [matrix-org/sliding-sync#47]
It takes around 8min for new deployments on matrix.org - we need to profile why:

```
13:15:13 INF retrieving global snapshot from database
13:23:26 INF retrieved global snapshot from database
13:23:26 INF creating handler
13:23:29 INF listening on 0.0.0.0:8080
```

**Comment by kegsay** [comment]
Did some analysis on this today and well, pictures.
<img width="1072" alt="Screenshot 2023-04-28 at 13 07 11" src="https://user-images.githubusercontent.com/7190048/235179350-58fb0d14-62e4-4f7f-acee-c22ea5c03a3a.png">

This is the function https://github.com/matrix-org/sliding-sync/blob/v0.99.2/state/storage.go#L747

**Comment by kegsay** [comment]
https://github.com/matrix-org/sliding-sync/pull/122 fixes this mostly. We can do better by grabbing more data per seq scan (e.g memberships) rather than 2x it with filters, but for now this will do.

**Comment by DMRobertson** [comment]
> #122 fixes this mostly. We can do better by grabbing more data per seq scan (e.g memberships) rather than 2x it with filters, but for now this will do.

This has helped, but we still see sluggish startup times of ~7 minutes.

```
2023-05-25T14:40:56.166396666Z stderr F 14:40:56 INF retrieving global snapshot from database
2023-05-25T14:47:34.073772877Z stderr F 14:47:34 INF retrieved global snapshot from database
```

**Comment by kegsay** [comment]
It's now 4-5 minutes, which is just about acceptable.
