### ISSUE TITLE
Do not echo the `range` from the client

### ISSUE THREAD

**Issue by Hywan** [matrix-org/sliding-sync#52]
Hi 👋,

Imagine the following scenario:

* The client is asking for a list with a range of `0..=9`, so 10 items,
* The server finds 1 room
* The server responds with a `SYNC` operation with a range of `[0, 9]`.

And this is wrong. It should reply with a range of `[0, 0]` because there is only one room found, not 10.

As discussed online, it's a bug. Right now, the server simply echoes back the range from the client's request, but it should compute a new range instead.

**Comment by kegsay** [comment]
`INVALIDATE` may have the same problem if your 2nd request then changes the sort/filter order because this just loops the previous range values https://github.com/matrix-org/sliding-sync/blob/main/sync3/handler/connstate.go#L238

**Comment by Hywan** [comment]
A simple workaround is fine if the returns `room_ids` starts from the beginning of the range, let's say: the client requests a range `10..=19`, and the `room_ids` contains 3 items, where the first maps to the position 10 and so on.
But if the `room_ids` contains 3 items, where their positions are 11, 15, 18, well, it's super hard to update the room lists correctly.

So this bug is critical :-).

**Comment by DMRobertson** [comment]
> But if the `room_ids` contains 3 items, where their positions are 11, 15, 18, well, it's super hard to update the room lists correctly. Actually it's impossible to guess anything.

The sliding sync protocol will never do this (if it does, that is a bug in the proxy has a bug). This would be emitted as three separate SYNC operations: `SYNC[11]`, `SYNC[15]` and `SYNC[18]`, see [the sliding window API description](https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md#sliding-window-api).

(I suppose it could also be emitted as three DELETE-INSERT pairs too, but that would be less efficient.)

Having said that, it should be feasible to make this change, and doing so should hopefully make the responses less surprising to everyone.

**Comment by Hywan** [comment]
Having 3 separate `SYNC` operations for non-contiguous positions, is fine for now. The bug fix is more important :-).
