### ISSUE TITLE
Missing messages after a batch of multiple messages are sent in short succession

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/sliding-sync#56]
> @kegsay I can see the problem on EW with SS too. I reproduce the same scenario by switching off and on my network while adding more messages to the room. Some messages are missing too.
>
> Steps to reproduce on EW is similar
> - Have a room 
> - Switch off the network
> - Send enough messages to this room (I sent 0..9 and a..q in my test)
> - Switch on the network
> -> Some messages are missing: 6, 7, 9, B, D, I, J, K:
>
> <img width="166" alt="image" src="https://user-images.githubusercontent.com/8418515/229757289-3a2b09a4-9432-443f-a765-b57e414da73c.png">

_Originally posted by @manuroe in https://github.com/matrix-org/matrix-rust-sdk/issues/1742#issuecomment-1495683074_

**Comment by DMRobertson** [comment]
Kegan's hunch: the poller is at fault here. It fails to accumulate all the messages. If you get 20 msgs quickly in a room, sync v2 will give you a gappy sync response. The proxy cannot handle gappy syncs. Suspect the poller's timeline limit isn't large enough.

If that's true, we _may_ see the log line https://github.com/matrix-org/sliding-sync/blob/main/state/accumulator.go#L156 (but we may not if there are no state events).

**Comment by DMRobertson** [comment]
> The main way to know if this is a problem is if refreshing the client fixes it or not. If it does fix on refresh then it isn't the poller at fault, the event DID get into the DB. If it doesn't, then it almost certainly IS the poller's fault.

@manuroe reports [here ](https://github.com/matrix-org/matrix-rust-sdk/issues/1742#issuecomment-1496131760) that a refresh fixed it.

**Comment by kegsay** [comment]
Thanks to @jplatte there's some test failures here https://gist.github.com/jplatte/25217087c8e6224855408485d0d45ed0 which begins to point to the problem. The key thing from these logs is:
 - Message 4 went missing, not the start or end.
 - The `num_live` int says `20`.
 - A normal successful test also has `num_live` of 20.

Server-side logs show 19x `INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing,receipts]=[0,1,0,0] to_device=0 user_id=@359d7d10-3f04-4a64-af92-f139145be04c:matrix-sdk.rs` lines for failing tests, 20x for successful tests (ignoring the initial one which has a state block `Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing,receipts]=[1,1,0,0] `).

I think my initial hunch was correct:

> the poller is at fault here. It fails to accumulate all the messages. If you get 20 msgs quickly in a room, sync v2 will give you a gappy sync response. The proxy cannot handle gappy syncs. Suspect the poller's timeline limit isn't large enough.

As these are just timeline events, we _won't_ see the log line I mentioned earlier. However, `limited: true` will be set so we can detect and log for this.

@manuroe seems to be hinting that it may have something to do with initial login, and would you believe it initial login is the _only time_ we adjust the timeline limit:
```go
func (v *HTTPClient) createSyncURL(since string, isFirst, toDeviceOnly bool) string {
	qps := "?"
	if isFirst { // first time syncing in this process
		qps += "timeout=0"
	} else {
		qps += "timeout=30000"
	}
	if since != "" {
		qps += "&since=" + since
	}

	timelineLimitOne := since == ""
	if timelineLimitOne || toDeviceOnly {
		room := map[string]interface{}{}
		if timelineLimitOne {
			room["timeline"] = map[string]interface{}{
				"limit": 1,
			}
		}
		if toDeviceOnly {
			// no rooms match this filter, so we get everything but room data
			room["rooms"] = []string{}
		}
		filter := map[string]interface{}{
			"room": room,
		}
		filterJSON, _ := json.Marshal(filter)
		qps += "&filter=" + url.QueryEscape(string(filterJSON))
	}
	return v.DestinationServer + "/_matrix/client/r0/sync" + qps
}
```

I feel like we're getting close, but I still don't understand precisely how this is failing, and why it is so flakey. I cannot repro this at all, yet @manuroe and @jplatte seem to be able to more reliably. Possible speed of machine?
