### ISSUE TITLE
When paginating through the room list in EX, the session expires due to too many msgs buffered up.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/sliding-sync#64]
EX builds from a week or so ago worked by paginating through the room list [0,20] then [20,40] then [40,60] etc, before then expanding to [0,6000] (assuming you have 6000 rooms).  During the pagination, after hitting around the 500 index, the proxy would reliably expire the session due to too many messages stacked up.

We fudged around this in https://github.com/matrix-org/sliding-sync/pull/57/files, but i'm very confused on why it was happening in the first place.

Or is the problem that more than 200 events arrived in other parts of the window that we weren't currently syncing, causing it to restart?  In which case, what's the solution if your window is small, but other events are arriving elsewhere on the account outside that window?

**Comment by kegsay** [comment]
> the problem that more than 200 events arrived in other parts of the window that we weren't currently syncing, causing it to restart?

Sorta. Events arrive constantly and are numerous (receipts, unread counts, typing are all treated as updates and count against the 200 buffer). The buffer is only consumed when the latest request has no data currently. If you constantly change the latest request, there will constantly be data to send back, so the buffer never gets consumed.

**Comment by kegsay** [comment]
This has been fixed now by sending fewer no-op updates - https://github.com/matrix-org/sliding-sync/commit/db2daa812cdf16306dc8f5ea9d88a34398a8c890
